type SelectOption = {
  label: string;
  value: string;
};

function toOptions(values: string[]): SelectOption[] {
  return values.map((value) => ({
    label: value,
    value,
  }));
}

const motorcycleBrands = [
  "Honda",
  "Yamaha",
  "Suzuki",
  "Kawasaki",
  "Vespa",
  "TVS",
  "Royal Enfield",
  "Benelli",
  "Keeway",
  "KTM",
  "Husqvarna",
  "Ducati",
  "BMW Motorrad",
  "Harley-Davidson",
  "Triumph",
  "Aprilia",
  "Piaggio",
  "SYM",
  "Kymco",
  "Viar",
  "United",
  "Alva",
  "Gesits",
  "Polytron",
  "Volta",
  "Selis",
  "Other",
];

export const motorcycleBrandOptions = toOptions(motorcycleBrands);

const motorcycleModelsByBrand: Record<string, string[]> = {
  Honda: [
    "C70",
    "C90",
    "Super Cub",
    "Astrea Star",
    "Astrea Prima",
    "Astrea Grand",
    "Astrea Legenda",
    "Supra",
    "Supra X",
    "Supra X 125",
    "Supra GTR 150",
    "Karisma",
    "Kirana",
    "Revo",
    "Blade",
    "Sonic 125",
    "Sonic 150R",
    "CS1",
    "Win",
    "Tiger",
    "MegaPro",
    "New MegaPro",
    "Verza",
    "CB150R StreetFire",
    "CB150 Verza",
    "CBR150R",
    "CBR250R",
    "CBR250RR",
    "CRF150L",
    "CRF250 Rally",
    "BeAT",
    "BeAT Street",
    "Spacy",
    "Scoopy",
    "Genio",
    "Vario 110",
    "Vario 125",
    "Vario 150",
    "Vario 160",
    "Vario Evo 160",
    "PCX 150",
    "PCX160",
    "ADV150",
    "ADV160",
    "Stylo 160",
    "Forza 250",
    "Monkey",
    "Super Cub C125",
    "CT125",
    "CB150X",
    "CB500F",
    "CB500X",
    "CB650R",
    "CBR500R",
    "CBR650R",
    "Rebel 500",
    "Gold Wing",
    "EM1 e:",
    "ICON e:",
    "CUV e:",
    "Other",
  ],

  Yamaha: [
    "V80",
    "RX-King",
    "RX-Z",
    "RX-Special",
    "F1ZR",
    "Crypton",
    "Vega",
    "Vega R",
    "Vega ZR",
    "Jupiter",
    "Jupiter Z",
    "Jupiter MX",
    "MX King 150",
    "Force",
    "Nouvo",
    "Nouvo Z",
    "Mio",
    "Mio Sporty",
    "Mio Soul",
    "Mio J",
    "Mio GT",
    "Mio M3",
    "Soul GT",
    "X-Ride",
    "X-Ride 125",
    "Fino",
    "Gear 125",
    "FreeGo",
    "Fazzio",
    "Grand Filano",
    "Lexi",
    "LEXi LX 155",
    "NMAX",
    "NMAX 155",
    "Aerox 155",
    "Aerox Alpha",
    "XMAX 250",
    "TMAX",
    "Byson",
    "Scorpio Z",
    "Vixion",
    "New Vixion",
    "Xabre",
    "MT-15",
    "MT-25",
    "R15",
    "R25",
    "WR155R",
    "XSR 155",
    "YZF-R1",
    "Other",
  ],

  Suzuki: [
    "A100",
    "RC100",
    "Crystal",
    "Tornado",
    "Satria 120R",
    "Shogun",
    "Shogun 110",
    "Shogun 125",
    "Smash",
    "Smash Titan",
    "Arashi",
    "Skywave",
    "Skydrive",
    "Spin",
    "Nex",
    "Nex II",
    "Address",
    "Avenis 125",
    "Burgman Street 125EX",
    "Satria F150",
    "Raider 150",
    "Thunder 125",
    "Thunder 250",
    "Inazuma 250",
    "GSX-R150",
    "GSX-S150",
    "GSX 150 Bandit",
    "V-Strom 250SX",
    "DR150",
    "Hayabusa",
    "Other",
  ],

  Kawasaki: [
    "Binter Merzy KZ200",
    "Ninja 150 R",
    "Ninja 150 RR",
    "Ninja 250",
    "Ninja 250SL",
    "Ninja ZX-25R",
    "Ninja ZX-4RR",
    "Ninja ZX-6R",
    "Ninja ZX-10R",
    "Ninja H2",
    "Kaze",
    "Kaze R",
    "Blitz",
    "Athlete",
    "D-Tracker 150",
    "D-Tracker 250",
    "KLX 150",
    "KLX150 S",
    "KLX150 BF",
    "KLX150 SM",
    "KLX230",
    "KLX250",
    "KX 65",
    "KX 85",
    "KX 112",
    "KX 250",
    "KX 450",
    "W175",
    "W250",
    "W800",
    "Estrella 250",
    "Z125 Pro",
    "Z250",
    "Z400",
    "Z650",
    "Z900",
    "Z1000",
    "Versys-X 250",
    "Versys 650",
    "Versys 1000",
    "Vulcan S",
    "Eliminator",
    "Other",
  ],

  Vespa: [
    "Vespa Super",
    "Vespa Sprint Classic",
    "Vespa PX",
    "Vespa Excel",
    "Vespa Corsa",
    "Vespa LX",
    "Vespa S",
    "Vespa Primavera",
    "Vespa Primavera S",
    "Vespa Sprint",
    "Vespa Sprint S",
    "Vespa GTS 150",
    "Vespa GTS Super Sport 150",
    "Vespa GTS Classic 150",
    "Vespa GTS Super Tech 250",
    "Vespa GTS 300 Super Tech",
    "Vespa GTV",
    "Vespa Elettrica",
    "Vespa 946",
    "Other",
  ],

  TVS: [
    "TVS Neo XR",
    "TVS Rockz",
    "TVS Dazz",
    "TVS XL 100",
    "TVS Max 125 Sport",
    "TVS Max 125 Semi Trail",
    "TVS Apache RTR 160",
    "TVS Apache RTR 180",
    "TVS Apache RTR 200",
    "TVS Ntorq 125",
    "TVS Callisto 110",
    "TVS Callisto 125",
    "TVS Ronin",
    "TVS iQube S",
    "Other",
  ],

  "Royal Enfield": [
    "Bullet 350",
    "Classic 350",
    "Meteor 350",
    "Hunter 350",
    "Goan Classic 350",
    "Himalayan",
    "Scram 411",
    "Guerrilla 450",
    "New Himalayan 450",
    "Interceptor 650",
    "Continental GT 650",
    "Super Meteor 650",
    "Shotgun 650",
    "Classic 650",
    "Bear 650",
    "Other",
  ],

  Benelli: [
    "Motobi 152",
    "Patagonian Eagle 250",
    "TNT 135",
    "TNT 15",
    "TNT 25",
    "TNT 249S",
    "TNT 250",
    "TNT 300",
    "Leoncino 250",
    "Leoncino 500",
    "TRK 251",
    "TRK 502",
    "Imperiale 400",
    "502C",
    "Other",
  ],

  Keeway: ["Shiny 150", "SCR 250V", "V250 FI", "Gleiten 125", "Other"],

  KTM: [
    "Duke 200",
    "Duke 250",
    "Duke 390",
    "RC 200",
    "RC 250",
    "RC 390",
    "Adventure 250",
    "Adventure 390",
    "EXC-F 250",
    "EXC-F 350",
    "EXC-F 450",
    "Other",
  ],

  Husqvarna: [
    "Svartpilen 200",
    "Svartpilen 250",
    "Svartpilen 401",
    "Vitpilen 250",
    "Vitpilen 401",
    "Norden 901",
    "Other",
  ],

  Ducati: [
    "Scrambler Icon",
    "Scrambler Nightshift",
    "Monster",
    "Hypermotard",
    "SuperSport",
    "Panigale V2",
    "Panigale V4",
    "Streetfighter V2",
    "Streetfighter V4",
    "Multistrada V2",
    "Multistrada V4",
    "Diavel",
    "XDiavel",
    "DesertX",
    "Other",
  ],

  "BMW Motorrad": [
    "G 310 R",
    "G 310 GS",
    "F 750 GS",
    "F 850 GS",
    "F 900 R",
    "F 900 XR",
    "R nineT",
    "R 1250 GS",
    "R 1300 GS",
    "S 1000 R",
    "S 1000 RR",
    "S 1000 XR",
    "C 400 X",
    "C 400 GT",
    "CE 04",
    "Other",
  ],

  "Harley-Davidson": [
    "Street 500",
    "Street 750",
    "Iron 883",
    "Forty-Eight",
    "Sportster S",
    "Nightster",
    "Softail Standard",
    "Street Bob",
    "Fat Bob",
    "Fat Boy",
    "Heritage Classic",
    "Low Rider S",
    "Road King",
    "Street Glide",
    "Road Glide",
    "Pan America",
    "Other",
  ],

  Triumph: [
    "Bonneville T100",
    "Bonneville T120",
    "Street Twin",
    "Speed Twin",
    "Thruxton",
    "Trident 660",
    "Street Triple",
    "Speed Triple",
    "Tiger Sport 660",
    "Tiger 850 Sport",
    "Tiger 900",
    "Tiger 1200",
    "Scrambler 900",
    "Scrambler 1200",
    "Rocket 3",
    "Other",
  ],

  Aprilia: [
    "SR GT 200",
    "RS 125",
    "RS 660",
    "Tuono 660",
    "Tuareg 660",
    "RSV4",
    "Tuono V4",
    "Other",
  ],

  Piaggio: ["Zip", "Liberty", "Medley", "Beverly", "MP3", "Other"],

  SYM: [
    "Mio 50",
    "Jet 14",
    "Jet X 125",
    "Cruisym 150",
    "Cruisym 300",
    "Maxsym 400",
    "Other",
  ],

  Kymco: [
    "Like 150i",
    "Racing King 150i",
    "X-Town 250i",
    "Downtown 250i",
    "Xciting 400i",
    "AK 550",
    "Other",
  ],

  Viar: [
    "Viar Star CX",
    "Viar Cross X 70",
    "Viar Cross X 100",
    "Viar Cross X 150",
    "Viar Cross X 200",
    "Viar Cross X 250",
    "Viar Q1",
    "Viar E-Cross",
    "Viar New Q1",
    "Other",
  ],

  United: [
    "United T1800",
    "United TX1800",
    "United TX3000",
    "United MX1200",
    "United C2000",
    "Other",
  ],

  Alva: ["Alva One", "Alva Cervo", "Alva N3", "Other"],

  Gesits: ["Gesits G1", "Gesits Raya", "Other"],

  Polytron: ["Polytron Fox-R", "Polytron Fox-S", "Polytron Fox-500", "Other"],

  Volta: [
    "Volta 401",
    "Volta 402",
    "Volta 403",
    "Volta Virgo",
    "Volta Mandala",
    "Other",
  ],

  Selis: [
    "Selis E-Max",
    "Selis Neo Scootic",
    "Selis Agats",
    "Selis Bromo",
    "Other",
  ],

  Other: ["Other"],
};

export const motorcycleModelOptionsByBrand: Record<string, SelectOption[]> =
  Object.fromEntries(
    Object.entries(motorcycleModelsByBrand).map(([brand, models]) => [
      brand,
      toOptions(models),
    ]),
  );

export const motorcycleYearOptions = toOptions(
  Array.from({ length: 60 }, (_, index) =>
    String(new Date().getFullYear() - index),
  ),
);
