export type SelectOption = {
  label: string;
  value: string;
};

function toOptions(values: string[]): SelectOption[] {
  return values.map((value) => ({
    label: value,
    value,
  }));
}

const partCategories = [
  "Ban",
  "Velg",
  "Knalpot",
  "Suspensi",
  "Rem",
  "CVT",
  "Engine",
  "ECU & Kelistrikan",
  "Lampu",
  "Body Kit",
  "Stang & Cockpit",
  "Spion",
  "Jok",
  "Rantai & Gir",
  "Oli & Fluids",
  "Aki",
  "Aksesoris",
  "Other",
];

export const partCategoryOptions = toOptions(partCategories);

const partBrandsByCategory: Record<string, string[]> = {
  Ban: [
    "IRC",
    "FDR",
    "Corsa",
    "Aspira",
    "Swallow",
    "Zeneos",
    "Maxxis",
    "Michelin",
    "Pirelli",
    "Dunlop",
    "Bridgestone",
    "Metzeler",
    "Mizzle",
    "Kingland",
    "Other",
    "Custom",
  ],

  Velg: [
    "RCB",
    "TDR",
    "TK Racing",
    "Chemco",
    "Power",
    "V Rossi",
    "DBS",
    "Scarlet",
    "VND",
    "Ride It",
    "KTC",
    "Enkei",
    "Excel",
    "Rossi",
    "Other",
    "Custom",
  ],

  Knalpot: [
    "R9",
    "Proliner",
    "WRX",
    "AHAU",
    "CLD",
    "Creampie",
    "Cream-pie",
    "Kawahara",
    "Norifumi",
    "Tsukigi",
    "DBS",
    "CMS",
    "HRP",
    "Abenk",
    "SKR",
    "Yoshimura",
    "Akrapovic",
    "SC Project",
    "Austin Racing",
    "Arrow",
    "Termignoni",
    "Two Brothers",
    "LeoVince",
    "Other",
    "Custom",
  ],

  Suspensi: [
    "YSS",
    "RCB",
    "KTC",
    "Daytona",
    "KYB",
    "Kayaba",
    "Showa",
    "Ohlins",
    "Scarlet",
    "DBS",
    "Ride It",
    "VND",
    "TDR",
    "Kawahara",
    "Fast Bikes",
    "Racing Boy",
    "Other",
    "Custom",
  ],

  Rem: [
    "Brembo",
    "Nissin",
    "Tokico",
    "RCB",
    "TDR",
    "KTC",
    "Daytona",
    "Ride It",
    "Scarlet",
    "Uma Racing",
    "Frando",
    "KYTACO",
    "Kawahara",
    "DBS",
    "SBS",
    "EBC",
    "BRT",
    "Other",
    "Custom",
  ],

  CVT: [
    "TDR",
    "Kawahara",
    "Uma Racing",
    "KTC",
    "RCB",
    "Daytona",
    "CLD",
    "BRT",
    "Koso",
    "Dr. Pulley",
    "Yamaha Genuine Parts",
    "Honda Genuine Parts",
    "Suzuki Genuine Parts",
    "Kawasaki Genuine Parts",
    "Other",
    "Custom",
  ],

  Engine: [
    "Uma Racing",
    "BRT",
    "TDR",
    "Kawahara",
    "CLD",
    "KTC",
    "Daytona",
    "TK Racing",
    "Faito",
    "YCS",
    "Rextor",
    "Koso",
    "Kitaco",
    "Takegawa",
    "UMA",
    "Yamaha Genuine Parts",
    "Honda Genuine Parts",
    "Suzuki Genuine Parts",
    "Kawasaki Genuine Parts",
    "Other",
    "Custom",
  ],

  "ECU & Kelistrikan": [
    "BRT",
    "Rextor",
    "Uma Racing",
    "Aracer",
    "Juken",
    "Koso",
    "Daytona",
    "Kawahara",
    "TDR",
    "RCB",
    "Yamaha Genuine Parts",
    "Honda Genuine Parts",
    "Suzuki Genuine Parts",
    "Kawasaki Genuine Parts",
    "Other",
    "Custom",
  ],

  Lampu: [
    "Autovision",
    "Osram",
    "Philips",
    "RTD",
    "AES",
    "Biled",
    "Hella",
    "Luminos",
    "Projie",
    "Koso",
    "JPA",
    "Nemo",
    "Other",
    "Custom",
  ],

  "Body Kit": [
    "Yamaha Genuine Parts",
    "Honda Genuine Parts",
    "Suzuki Genuine Parts",
    "Kawasaki Genuine Parts",
    "Bikers",
    "KTC",
    "RCB",
    "TDR",
    "Kawahara",
    "JPA",
    "Nemo",
    "Custom",
    "Other",
    "Custom",
  ],

  "Stang & Cockpit": [
    "RCB",
    "TDR",
    "KTC",
    "Scarlet",
    "Ride It",
    "Bikers",
    "Protaper",
    "Renthal",
    "Rizoma",
    "Domino",
    "Koso",
    "Daytona",
    "Kawahara",
    "Other",
    "Custom",
  ],

  Spion: [
    "Rizoma",
    "Koso",
    "RCB",
    "TDR",
    "KTC",
    "Bikers",
    "Scarlet",
    "Ride It",
    "Daytona",
    "JPA",
    "Nemo",
    "Custom",
    "Other",
    "Custom",
  ],

  Jok: [
    "MBtech",
    "Murano",
    "Black Sweet",
    "VND",
    "Custom",
    "Yamaha Genuine Parts",
    "Honda Genuine Parts",
    "Suzuki Genuine Parts",
    "Kawasaki Genuine Parts",
    "Other",
    "Custom",
  ],

  "Rantai & Gir": [
    "SSS",
    "DID",
    "RK",
    "KMC",
    "TK Racing",
    "TDR",
    "Kawahara",
    "Daytona",
    "Aspira",
    "Sinnob",
    "Yamaha Genuine Parts",
    "Honda Genuine Parts",
    "Suzuki Genuine Parts",
    "Kawasaki Genuine Parts",
    "Other",
    "Custom",
  ],

  "Oli & Fluids": [
    "Yamalube",
    "AHM Oil",
    "Suzuki Genuine Oil",
    "Kawasaki Genuine Oil",
    "Motul",
    "Shell Advance",
    "Castrol",
    "Federal Oil",
    "Pertamina Enduro",
    "Top 1",
    "Evalube",
    "Liqui Moly",
    "Repsol",
    "Idemitsu",
    "Mobil",
    "Other",
    "Custom",
  ],

  Aki: [
    "GS Astra",
    "Yuasa",
    "Motobatt",
    "Aspira",
    "Bosch",
    "Incoe",
    "Amaron",
    "Daytona",
    "RCB",
    "Other",
    "Custom",
  ],

  Aksesoris: [
    "RCB",
    "TDR",
    "KTC",
    "Bikers",
    "Rizoma",
    "Koso",
    "Daytona",
    "Kawahara",
    "Scarlet",
    "Ride It",
    "VND",
    "JPA",
    "Nemo",
    "Custom",
    "Other",
    "Custom",
  ],

  Other: ["Other"],
};

export const partBrandOptionsByCategory: Record<string, SelectOption[]> =
  Object.fromEntries(
    Object.entries(partBrandsByCategory).map(([category, brands]) => [
      category,
      toOptions(brands),
    ]),
  );
